"""TX3 ROM Builder - Remote Management Module
Integrates Remote Management features into ROM Builder v0.7.0.
Adds checkbox UI, agent injection, Tailscale VPN config, auto ADB, and init scripts.

Version: 1.0.0
"""
from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional


@dataclass
class RemoteManagementConfig:
    """Configuration for Remote Management injection into ROM."""
    enabled: bool = True
    auto_start: bool = True
    tailscale: bool = True
    tailscale_authkey: str = "tskey-auth-kQEiimCRMm11CNTRL-K99q54JBSrEwPpjq7r7pqENLesKEXd4N"
    rustdesk: bool = True
    live_remote: bool = True
    mouse_keyboard_dpad: bool = True
    file_transfer: bool = True
    remote_adb: bool = True
    apk_install: bool = True
    auto_reconnect: bool = True
    resource_guard: bool = True
    watchdog: bool = True
    auto_adb: bool = True  # Auto-enable ADB on first flash

    # Server configuration
    server_url: str = ""
    bootstrap_token: str = ""

    # Profile
    profile: str = "auto"  # auto | 540p20 | 720p20 | 720p25 | 720p30

    # Agent files location (relative to module directory)
    agent_files_dir: str = ""

    def to_dict(self) -> dict:
        return {
            "enabled": self.enabled,
            "auto_start": self.auto_start,
            "tailscale": self.tailscale,
            "tailscale_authkey": self.tailscale_authkey,
            "rustdesk": self.rustdesk,
            "live_remote": self.live_remote,
            "mouse_keyboard_dpad": self.mouse_keyboard_dpad,
            "file_transfer": self.file_transfer,
            "remote_adb": self.remote_adb,
            "apk_install": self.apk_install,
            "auto_reconnect": self.auto_reconnect,
            "resource_guard": self.resource_guard,
            "watchdog": self.watchdog,
            "auto_adb": self.auto_adb,
            "server_url": self.server_url,
            "bootstrap_token": self.bootstrap_token,
            "profile": self.profile,
        }

    @classmethod
    def from_dict(cls, data: dict) -> RemoteManagementConfig:
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


# Agent component files to inject into ROM system partition
AGENT_COMPONENTS = {
    "tx3-agent": {
        "source": "agent/tx3-agent.sh",
        "destination": "/bin/tx3-agent",
        "mode": "0100755",
        "description": "Main agent daemon",
    },
    "tx3-supervisor": {
        "source": "supervisor/tx3-supervisor.sh",
        "destination": "/bin/tx3-supervisor",
        "mode": "0100755",
        "description": "Process supervisor & resource guard",
    },
    "tx3-stream": {
        "source": "stream/tx3-stream.sh",
        "destination": "/bin/tx3-stream",
        "mode": "0100755",
        "description": "Screen capture & H.264 streaming",
    },
    "tx3-file": {
        "source": "file-transfer/tx3-file.sh",
        "destination": "/bin/tx3-file",
        "mode": "0100755",
        "description": "File transfer service",
    },
    "tx3-init": {
        "source": "init/tx3-init.sh",
        "destination": "/bin/tx3-init",
        "mode": "0100755",
        "description": "Boot init script",
    },
    "tailscaled": {
        "source": "binaries/tailscaled",
        "destination": "/bin/tailscaled",
        "mode": "0100755",
        "description": "Tailscale Userspace Daemon Binary (ARM)",
    },
    "tailscale": {
        "source": "binaries/tailscale",
        "destination": "/bin/tailscale",
        "mode": "0100755",
        "description": "Tailscale CLI Binary (ARM)",
    },
}


def get_agent_base_dir() -> Path:
    """Get the base directory for agent component source files."""
    # Look relative to this module, then in common locations
    module_dir = Path(__file__).resolve().parent
    candidates = [
        module_dir / "agent-files",
        module_dir.parent.parent.parent / "android-agent",
        Path("/home/dts/androidbox/tx3-platform/android-agent"),
    ]
    for candidate in candidates:
        if candidate.is_dir():
            return candidate
    return module_dir / "agent-files"


def generate_bootstrap_config(config: RemoteManagementConfig) -> str:
    """Generate bootstrap.conf content for injection into ROM."""
    lines = [
        "# TX3 Bootstrap Configuration",
        "# Auto-generated by ROM Builder Remote Management module",
        f"PROVISION_SERVER={config.server_url}",
        f"BOOTSTRAP_TOKEN={config.bootstrap_token}",
        "",
        f"AGENT_AUTO_START={'1' if config.auto_start else '0'}",
        f"TAILSCALE_AUTO_START={'1' if config.tailscale else '0'}",
        f"ADB_AUTO_ENABLE={'1' if config.auto_adb else '0'}",
        "ADB_TCP_PORT=5555",
        "",
        f"STREAM_DEFAULT_PROFILE={config.profile}",
        f"STREAM_MAX_FPS={'25' if config.profile == 'auto' else config.profile.split('p')[1] if 'p' in config.profile else '25'}",
        f"STREAM_MAX_BITRATE=2500",
        "",
        f"RESOURCE_GUARD_ENABLED={'1' if config.resource_guard else '0'}",
        "SOFT_RAM_PERCENT=80",
        "HARD_RAM_PERCENT=90",
        "SOFT_TEMP_C=75",
        "HARD_TEMP_C=85",
    ]
    return "\n".join(lines) + "\n"


def generate_init_script(config: RemoteManagementConfig) -> str:
    """Generate the preinstall.sh additions for auto-start."""
    parts = [
        "",
        "# TX3 REMOTE MANAGEMENT START",
        "# Wait for boot completion",
        "tx3_i=0",
        'while [ "$(getprop sys.boot_completed)" != "1" ] && [ $tx3_i -lt 120 ]; do sleep 2; tx3_i=$((tx3_i+1)); done',
        "sleep 5",
        "",
    ]

    if config.tailscale:
        parts.extend([
            "# Tailscale Auto-Start & Auto-Connect",
            "mkdir -p /dev/net 2>/dev/null",
            "[ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200 2>/dev/null",
            "chmod 0666 /dev/net/tun 2>/dev/null",
            "mkdir -p /data/adb/tailscale 2>/dev/null",
            "if [ -f /system/bin/tailscaled ]; then",
            "    pkill -9 tailscaled 2>/dev/null",
            "    /system/bin/tailscaled --state=/data/adb/tailscale/tailscaled.state --socket=/data/adb/tailscale/tailscaled.sock --tun=userspace-networking > /data/adb/tailscale/tailscaled.log 2>&1 &",
            "    sleep 3",
            "    /system/bin/tailscale --socket=/data/adb/tailscale/tailscaled.sock up --authkey=" + config.tailscale_authkey + " --hostname=tx3-box-$(getprop ro.serialno || cat /sys/class/net/eth0/address 2>/dev/null | tr -d ':') --accept-dns=false &",
            "fi",
            "",
        ])

    
    if config.auto_adb:
        parts.extend([
            "# Auto-enable ADB & Memory/Thermal Optimization for 24/7 Stability",
            "setprop persist.sys.usb.config adb",
            "setprop service.adb.tcp.port 5555",
            "settings put global adb_enabled 1 2>/dev/null",
            "setprop persist.adb.tcp.enable 1",
            "# Tối ưu hóa bộ nhớ RAM & LowMemoryKiller cho Android Box chạy 24/7",
            "sysctl -w vm.dirty_background_ratio=5 2>/dev/null",
            "sysctl -w vm.dirty_ratio=10 2>/dev/null",
            "sysctl -w vm.vfs_cache_pressure=150 2>/dev/null",
            "stop adbd 2>/dev/null",
            "start adbd 2>/dev/null",
            "",
        ])

    if config.auto_start:
        parts.extend([
            "# Create TX3 directories",
            "mkdir -p /data/tx3/logs /data/tx3/bin /data/tx3/transfers",
            "",
            "# Copy bootstrap config if first boot",
            'if [ ! -f /data/tx3/bootstrap.conf ]; then',
            '    cp /system/etc/tx3/bootstrap.conf /data/tx3/bootstrap.conf 2>/dev/null',
            'fi',
            "",
            "# Start TX3 Agent",
            'if [ -f /system/bin/tx3-agent ]; then',
            '    tx3_pid=""',
            '    if [ -f /data/tx3/tx3-agent.pid ]; then',
            '        tx3_pid=$(cat /data/tx3/tx3-agent.pid)',
            '        kill -0 "$tx3_pid" 2>/dev/null || tx3_pid=""',
            '    fi',
            '    if [ -z "$tx3_pid" ]; then',
            '        /system/bin/tx3-agent &',
            '    fi',
            'fi',
            "",
        ])

    parts.append("# TX3 REMOTE MANAGEMENT END")
    return "\n".join(parts) + "\n"


def generate_debugfs_commands(
    config: RemoteManagementConfig,
    work_dir: Path,
    progress: Optional[Callable] = None,
) -> list[str]:
    """Generate debugfs commands to inject Remote Management into system EXT4 image.

    Returns a list of debugfs commands to be executed against the system.raw image.
    """
    from rombuilder.core.ext4 import cygwin_path, safe_name

    commands = []
    agent_base = get_agent_base_dir()

    if progress:
        progress(0, "Preparing Remote Management files")

    # ── 1. Create directories ──
    dirs_to_create = ["/etc/tx3", "/bin"]
    for d in dirs_to_create:
        commands.append(f"mkdir {d}")
        commands.append(f"ea_set {d} security.selinux u:object_r:system_file:s0")

    # ── 2. Inject agent binaries ──
    staged_dir = work_dir / "tx3-staged"
    staged_dir.mkdir(parents=True, exist_ok=True)

    components = list(AGENT_COMPONENTS.items())
    total = len(components) + 2  # +2 for bootstrap.conf and init script

    for idx, (name, info) in enumerate(components):
        if not config.enabled:
            break

        # Check feature flags
        if name == "tx3-stream" and not config.live_remote:
            continue
        if name == "tx3-file" and not config.file_transfer:
            continue
        if name == "tx3-supervisor" and not config.watchdog:
            continue

        source = agent_base / info["source"]
        staged = staged_dir / name

        if source.exists():
            shutil.copy2(source, staged)
        else:
            # Create placeholder if source not found
            staged.write_text(f"#!/system/bin/sh\n# Placeholder for {name}\n# Source: {source}\nexit 0\n")

        target = info["destination"]
        parent = target.rsplit("/", 1)[0]
        filename = target.rsplit("/", 1)[1]

        commands.extend([
            f"cd {parent}",
            f"rm {filename}",
            f'write "{cygwin_path(staged)}" {filename}',
            "cd /",
            f"set_inode_field {target} mode {info['mode']}",
            f"ea_set {target} security.selinux u:object_r:system_file:s0",
        ])

        if progress:
            progress(int((idx + 1) * 80 / total), f"Injecting {info['description']}")

    # ── 3. Inject bootstrap config ──
    bootstrap_content = generate_bootstrap_config(config)
    bootstrap_file = staged_dir / "bootstrap.conf"
    bootstrap_file.write_text(bootstrap_content, encoding="utf-8", newline="\n")

    commands.extend([
        "cd /etc/tx3",
        "rm bootstrap.conf",
        f'write "{cygwin_path(bootstrap_file)}" bootstrap.conf',
        "cd /",
        "set_inode_field /etc/tx3/bootstrap.conf mode 0100644",
        "ea_set /etc/tx3/bootstrap.conf security.selinux u:object_r:system_file:s0",
    ])

    if progress:
        progress(85, "Injecting bootstrap configuration")

    # ── 4. ROM metadata ──
    metadata = {
        "remote_management": True,
        "rm_version": "1.0.0",
        "agent_version": "1.0.0",
        "protocol_version": 1,
        "features": {
            "auto_start": config.auto_start,
            "tailscale": config.tailscale,
            "live_remote": config.live_remote,
            "file_transfer": config.file_transfer,
            "remote_adb": config.remote_adb,
            "resource_guard": config.resource_guard,
            "watchdog": config.watchdog,
            "auto_adb": config.auto_adb,
        },
        "profile": config.profile,
    }
    meta_file = staged_dir / "tx3_rom_meta.json"
    meta_file.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    commands.extend([
        "cd /etc/tx3",
        "rm tx3_rom_meta.json",
        f'write "{cygwin_path(meta_file)}" tx3_rom_meta.json',
        "cd /",
        "set_inode_field /etc/tx3/tx3_rom_meta.json mode 0100644",
        "ea_set /etc/tx3/tx3_rom_meta.json security.selinux u:object_r:system_file:s0",
    ])

    if progress:
        progress(95, "Finalizing Remote Management injection")

    return commands


def modify_preinstall_script(existing_content: str, config: RemoteManagementConfig) -> str:
    """Modify existing preinstall.sh to add TX3 Remote Management auto-start.

    Preserves existing content and appends/replaces the TX3 block.
    """
    # Remove any existing TX3 block
    cleaned = re.sub(
        r"\n?# TX3 REMOTE MANAGEMENT START.*?# TX3 REMOTE MANAGEMENT END\n?",
        "\n",
        existing_content,
        flags=re.DOTALL,
    )

    if config.enabled:
        cleaned += generate_init_script(config)

    return cleaned
